services:
  devicemonitoringwebapi:
    image: ${DOCKER_REGISTRY-}devicemonitoringwebapi
    build:
      context: .
      dockerfile: DeviceMonitoringWebApi/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DeviceSessionsDatabase=Host=postgres_sessions;Port=5432;Database=DeviceSessions;Username=postgres;Password=admin;
    depends_on:
      postgres_sessions:
        condition: service_healthy

  postgres_sessions:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=DeviceSessions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata_sessions:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata_sessions:
